apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "renovate-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "renovate-operator.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "renovate-operator.fullname" . }}
    spec:
      serviceAccountName: {{ include "renovate-operator.serviceAccountName" . }}
      {{- with .Values.securityContext.pod }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: renovate-operator
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext.container }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JOB_TIMEOUT_SECONDS
              value: {{ .Values.config.defaultJobActiveDeadlineSeconds | quote }}
            - name: JOB_BACKOFF_LIMIT
              value: {{ .Values.config.defaultJobBackoffLimit | quote }}
            - name: SERVER_PORT
              value: "8081"
            {{- if .Values.webhook.enabled }}
            - name: WEBHOOK_SERVER_PORT
              value: {{ .Values.webhook.port | quote }}
            - name: WEBHOOK_SERVER_ENABLED
              value: "true"
            {{- end }}
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
            {{- if .Values.webhook.enabled }}
            - containerPort: {{ .Values.webhook.port }}
              name: webhook
              protocol: TCP
            {{- end }}
