{{- with .Values.route }}
{{- range $routeName, $routeConfig := . }}
{{- if (default true $routeConfig.enabled) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: {{ $routeConfig.kind | default "HTTPRoute" }}
metadata:
  name: {{ include "renovate-operator.fullname" $ }}{{ if $routeConfig.nameOverride }}-{{ $routeConfig.nameOverride }}{{ else if ne $routeName "main" }}-{{ $routeName }}{{ end }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ include "renovate-operator.fullname" $ }}
    {{- with $routeConfig.labels }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
  annotations:
  {{- with (default dict $routeConfig.annotations) }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $routeConfig.parentRefs }}
  parentRefs:
    {{- toYaml $routeConfig.parentRefs | nindent 4 }}
  {{- end }}
  {{- if $routeConfig.hostnames }}
  hostnames:
    {{- range $routeConfig.hostnames }}
    - {{ tpl . $ | quote }}
    {{- end }}
  {{- end }}
  {{- if $routeConfig.rules }}
  rules:
    {{- range $ruleIndex, $rule := $routeConfig.rules }}
    - {{- if $rule.name }}
      name: {{ $rule.name | quote }}
      {{- end }}
      {{- if $rule.matches }}
      matches:
        {{- toYaml $rule.matches | nindent 8 }}
      {{- end }}
      {{- if $rule.backendRefs }}
      backendRefs:
        {{- toYaml $rule.backendRefs | nindent 8 }}
      {{- else }}
      backendRefs:
        - name: {{ include "renovate-operator.fullname" $ }}
          port: 8081
          weight: 1
      {{- end }}
      {{- if $rule.filters }}
      filters:
        {{- toYaml $rule.filters | nindent 8 }}
      {{- end }}
      {{- if $rule.timeouts }}
      timeouts:
        {{- toYaml $rule.timeouts | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
