name: GO lint & test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: MEGA-FAST

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.2'

    - name: build
      run: |
        cd src

        go mod download

        go build ./...
  test:
    needs: [build]
    runs-on: MEGA-FAST

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.2'

    - name: lint and test
      run: |
        cd src
        go mod download
        go test ./... -v

  # lint:
  #   needs: [build]
  #   runs-on: MEGA-FAST

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

  #   - name: Set up Go
  #     uses: actions/setup-go@v5
  #     with:
  #       go-version: '>=1.23.2'

  #   - name: lint and test
  #     run: |
  #       cd src
  #       go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  #       go mod download

  #       golangci-lint run --timeout 10m
